### ISSUE TITLE
Pricing in Info

### ISSUE THREAD

**Issue by dbustelo** [chrisbee32/shufflestream#19]
Pricing
Add Saatchiart.com style pricing (same text for each image) 

Lower right
top line “$1,000”
bottom line “Prints from $50”; 

Lower left
 “Add to Cart” in box like current "Marketplace" box

![screen shot 2015-04-12 at 8 21 58 pm](https://cloud.githubusercontent.com/assets/11659272/7109993/5e763ad4-e15e-11e4-81b5-12ad87838e0a.png)

**Comment by kylezinter** [comment]
Check out what I've done when you get a chance and let me know what you think.

**Comment by dbustelo** [comment]
Looks great!

**Comment by kylezinter** [comment]
Change prices and fix styling overlap, allow to vertically grow more

**Comment by kylezinter** [comment]
Out of date and this was completed. Newer tasks opened for this space already.
