### ISSUE TITLE
Performance: Set up DynamoDB for metadata 

### ISSUE THREAD

**Issue by kylezinter** [chrisbee32/shufflestream#2]
Already seeing the calls to AWS be unacceptably slow. Need to look into what we can do here. Front-end can provide some "illusion" and cover but will still need the call to be faster.

**Comment by ctrlbee** [comment]
Yep, already have a few things in mind. Working on replacing the meta data storage with DynamoDB and will look into cloudfront to deliver the images.

**Comment by ctrlbee** [comment]
System is now working off of DynamoDb for metadata and channels.
