### ISSUE TITLE
Adjust width Fashion Edge Cover Image in Mosaic (blonde extreme hairdo)

### ISSUE THREAD

**Issue by dbustelo** [chrisbee32/shufflestream#39]
To make this image slightly wider, more in line with the bottom row far left/far right images

Sorrrrrry to add another... We talked about last Sunday but forgot to add here. I don't know how involved so if you can this week...

**Comment by kylezinter** [comment]
@dbustelo go ahead and check the live heroku site, this should be done already now.

**Comment by dbustelo** [comment]
It did, thanks! And had a demo this morning so was great. Something weird happening with the Detail page, many images are showing all the fields as Null or show correct data then reverting to null. Guessing you're working on it.... ?

dot bustelo
c +1-646-729-9019

**Comment by kylezinter** [comment]
Hmm weird. I wasn't seeing that but I have seen it happen before. I'll look into it. Can you open up another issue on this topic with your specific repro steps?

Date: Tue, 21 Apr 2015 10:04:28 -0700

**Comment by dbustelo** [comment]
Sure, and hank you.  I’ll pay closer attention though seems it wasn’t much more than selecting “i"

**Comment by kylezinter** [comment]
Closing this for now as this is complete and the other bug was opened.
